name: hello
on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'jdk'
          java-version: 11
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - uses: nyurik/action-setup-nginx@v1
        id: nginx
      - run: |
          echo "Hello, world!" > "${{ steps.nginx.outputs.html-dir }}/index.html"
